"""empty message

Revision ID: 3e1657dff0fe
Revises: f6c5ee9d6c83
Create Date: 2023-02-23 09:48:07.444922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e1657dff0fe'
down_revision = 'f6c5ee9d6c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renting_ends', sa.DateTime(), nullable=True))
        batch_op.alter_column('rented',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('rented',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('renting_ends')

    # ### end Alembic commands ###
