"""empty message

Revision ID: 648a942a200d
Revises: 4e86ec883bb6
Create Date: 2023-03-03 10:15:55.452875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '648a942a200d'
down_revision = '4e86ec883bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('number_of_occupied', sa.Integer(), nullable=True))
        batch_op.drop_column('free_amount_of_seats')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_amount_of_seats', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('number_of_occupied')
        batch_op.drop_column('free_amount')

    # ### end Alembic commands ###
