"""empty message

Revision ID: 95b3e580f4e0
Revises: 905532db629c
Create Date: 2023-03-03 09:44:18.867051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95b3e580f4e0'
down_revision = '905532db629c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.create_foreign_key(None, 'hotel', ['room_id'], ['id'])

    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_count_clients', sa.Integer(), nullable=False))
        batch_op.alter_column('area',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('price_for_a_night',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('busy')
        batch_op.drop_column('number_of_beds')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_beds', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('busy', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('price_for_a_night',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('area',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('max_count_clients')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_column('room_id')

    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('rented', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('renting_ends', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='orders_ibfk_1'),
    sa.ForeignKeyConstraint(['room_id'], ['hotel.id'], name='orders_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
