"""empty message

Revision ID: 9f863c4f4f39
Revises: 648a942a200d
Create Date: 2023-03-03 11:25:10.827039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f863c4f4f39'
down_revision = '648a942a200d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.alter_column('free_amount',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('number_of_occupied',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.alter_column('number_of_occupied',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('free_amount',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
