"""empty message

Revision ID: df17b5432859
Revises: 3e1657dff0fe
Create Date: 2023-02-23 10:33:36.490928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df17b5432859'
down_revision = '3e1657dff0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('rented',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('renting_ends',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('on_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_days', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('renting_ends',
               existing_type=sa.String(length=20),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('rented',
               existing_type=sa.String(length=20),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
