"""empty message

Revision ID: 4e86ec883bb6
Revises: 95b3e580f4e0
Create Date: 2023-03-03 10:08:28.818657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e86ec883bb6'
down_revision = '95b3e580f4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_amount_clients', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('free_amount_of_seats', sa.Integer(), nullable=True))
        batch_op.drop_column('max_count_clients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_count_clients', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('free_amount_of_seats')
        batch_op.drop_column('max_amount_clients')

    # ### end Alembic commands ###
